---
# Properties are set to the following:
# isHidden: false   -- This allows it to be seen in the map editor and menus.
# isSpawnable: true -- This allows the Unit: Spawn event use the unit.
# classIcon:        -- A bug in modifyingUnitClasses makes it wrongly override the classIcon based on the units' names.
#                      These are manually specified to prevent erroneous changes.
modifyingUnitClasses:
  # Groove units
  - id: crystal # Emeric's Crystal
    replace: 
      isHidden: false
      classIcon: unit_icons_summon
  - id: vine # Greenfinger's Vine
    replace:
      isHidden: false
      classIcon: unit_icons_summon  
  - id: drone # Koji's Sparrow Bomb
    replace:
      isHidden: false
      classIcon: unit_icons_summon  
  - id: shadow_vesper # Shadow Sister
    replace:
      isHidden: false
      classIcon: unit_icons_summon
  
  # Commander units
  - id: commander_vesper_boss
    replace:
      isHidden: false
      appearsInLists: true
      isSpawnable: true
  - id: commander_orla
    replace:
      isHidden: false
      isSpawnable: true
  - id: commander_errol
    replace:
      isHidden: false
      isSpawnable: true
  
  # Other hidden units
  - id: ghost_mercival # Mercival's ghost (seen in Act 3, Mission 2)
    replace:
      isHidden: false    
  - id: garrison # Garrison (the attacker for buildings)
    replace:
      isHidden: false
      isSpawnable: true
...
