---
# Properties are set to the following:
# isHidden: false                -- This allows it to be seen in the map editor and menus.
# isSpawnable: true              -- This allows the Unit: Spawn event use the unit.
# classIcon:                     -- A bug in modifyingUnitClasses makes it wrongly override the classIcon based on the units' names.
#                                   These are manually specified to prevent erroneous changes.
# isHiddenInCutsceneEditor: true -- This allows it to be chosen in the Cutscene Editor as an 'actor'.
modifyingUnitClasses:
  # Naval units
  - id: travelboat # Barge
    replace:
      isHiddenInCutsceneEditor: true
  - id: turtle # Turtle
    replace:
      isHiddenInCutsceneEditor: true
  - id: harpoonship # Harpoon Ship
    replace:
      isHiddenInCutsceneEditor: true
  - id: warship # Warship
    replace:
      isHiddenInCutsceneEditor: true
      
  # Groove units
  - id: crystal # Emeric's Crystal
    replace: 
      isHidden: false
      classIcon: unit_icons_summon
  - id: vine # Greenfinger's Vine
    replace:
      isHidden: false
      classIcon: unit_icons_summon  
  - id: drone # Koji's Sparrow Bomb
    replace:
      isHidden: false
      classIcon: unit_icons_summon  
  - id: shadow_vesper # Shadow Sister
    replace:
      isHidden: false
      classIcon: unit_icons_summon
  
  # Commander units
  - id: commander_vesper_boss # Vesper_(Boss)
    replace:
      isHidden: false
      appearsInLists: true
      isSpawnable: true
  - id: commander_orla # Orla (solo)
    replace:
      isHidden: false
      isSpawnable: true
  - id: commander_errol # Errol (solo)
    replace:
      isHidden: false
      isSpawnable: true
  
  # Other hidden units
  - id: ghost_mercival # Mercival's ghost (seen in Act 3, Mission 2)
    replace:
      isHidden: false
      isSpawnable: true
  - id: garrison # Garrison (the attacker for buildings)
    replace:
      isHidden: false
      isSpawnable: true
...
