---
# Override each decoration with the hidden setting set to false to allow them to be seen in the editor.

decorations:
  - id: waterfall_down2_lava
    hidden: false
    layer: above_water
    snapToGrid: true
    animation:
      undefined: decoration/water/waterfall_down02_lava
  - id: waterfall_down3_lava
    hidden: false
    layer: above_water
    snapToGrid: true
    animation:
      undefined: decoration/water/waterfall_down03_lava   
  - id: volcano_pillar_1
    hidden: false
    layer: units
    animation:
      undefined: decoration/ground/volcano_pillar_1
  - id: volcano_pillar_2
    hidden: false
    layer: units
    animation:
      undefined: decoration/ground/volcano_pillar_2
  - id: volcano
    hidden: false
    layer: ground
    animation:
      undefined: decoration/ground/volcano
  - id: lavarock1
    hidden: false
    layer: ground
    animation:
      undefined: decoration/water/lavarock1
  - id: lavarock2
    hidden: false
    layer: ground
    animation:
      undefined: decoration/water/lavarock2   
  - id: lavarock3
    hidden: false
    layer: ground
    animation:
      undefined: decoration/water/lavarock3
  - id: lavarock4
    hidden: false
    layer: ground
    animation:
      undefined: decoration/water/lavarock4
  - id: lavabubble
    hidden: false
    layer: ground
    animation:
      undefined: decoration/water/lavabubble      
...
