---
# These location highlights are controller/keyboard controls, as specified in location_highlight_buttons.yaml (not changed in this mod).
# The displayed graphic varies between PC, Playstation, Switch (Joycon), Switch (controller), and Xbox

# btm_primary_low is not unhidden because it is completely identical to btn_primary, offering no additional functionality. 
location_highlights:
  - id: btn_primary
    hidden: false
    layers:
      - button: primary
        placement: center
        layer: above
        offset: [0,0]
      - animation: "world/locations/tutorial_cross"
        placement: all
        layer: underArrow
        alphaPulse: false
  - id: btn_primary_low
    hidden: true # Left intentionally hidden.
    layers:
      - button: primary
        placement: center
        layer: above
        offset: [0,0]
      - animation: "world/locations/tutorial_cross"
        placement: all
        layer: underArrow
        alphaPulse: false
  - id: btn_cancel
    hidden: false
    layers:
      - button: cancel
        placement: center
        layer: above
        offset: [0,0]
      - animation: "world/locations/tutorial_cross"
        placement: all
        layer: underArrow
        alphaPulse: false
  - id: btn_primary_below
    hidden: false
    layers:
      - button: primary_below
        placement: center
        layer: above
        offset: [0,0]
      - animation: "world/locations/tutorial_cross"
        placement: all
        layer: underArrow
        alphaPulse: false
  - id: btn_cancel_below
    hidden: false
    layers:
      - button: cancel_below
        placement: center
        layer: above
        offset: [0,0]
      - animation: "world/locations/tutorial_cross"
        placement: all
        layer: underArrow
        alphaPulse: false
  - id: btn_overview
    hidden: false
    layers:
      - button: btn_overview
        placement: center
        layer: above
        offset: [0,0]

... 
