---

music:

  - id: victory
    name: music_name_victory
    audioEvent: music/victory_only
    availableOnMap: true
  - id: defeat
    name: music_name_defeat
    audioEvent: music/defeat_only
    availableOnMap: true
  - id: main_theme
    name: music_name_main_theme
    audioEvent: music/main_theme
    jukebox:
      animation: units/soldier/cherrystone/battle_soldier_cherrystone
      animationSequence: emote_dance
      playerColour: red
      skinColour: typeII
    availableOnMap: true
  - id: intro
    name: music_name_intro
    audioEvent: music/intro
    jukebox:
      animation: units/soldier/cherrystone/battle_soldier_cherrystone
      animationSequence: emote_dance
      playerColour: red
      skinColour: typeII
    availableOnMap: true
    
  - id: no_ambience
    name: music_name_none
    isAmbience: true
  - id: desert_ambience
    name: music_name_desert_ambience
    audioEvent: environmental/desertAmbience
    isAmbience: true
  - id: desert_river_ambience
    name: music_name_desert_river_ambience
    audioEvent: environmental/desertRiverAmbience
    isAmbience: true
    hidden: true
  - id: field_ambience
    name: music_name_field_ambience
    audioEvent: environmental/fieldAmbience
    isAmbience: true
  - id: field_river_ambience
    name: music_name_field_river_ambience
    audioEvent: environmental/fieldRiverAmbience
    isAmbience: true
    hidden: true
  - id: forest_ambience
    name: music_name_forest_ambience
    audioEvent: environmental/forestAmbience
    isAmbience: true
  - id: mountain_ambience
    name: music_name_mountain_ambience
    audioEvent: environmental/mountainAmbience
    isAmbience: true
  - id: ocean_ambience
    name: music_name_ocean_ambience
    audioEvent: environmental/oceanAmbience
    isAmbience: true
  - id: snow_ambience
    name: music_name_snow_ambience
    audioEvent: environmental/snowAmbience
    isAmbience: true
  - id: snow_river_ambience
    name: music_name_snow_river_ambience
    audioEvent: environmental/snowRiverAmbience
    isAmbience: true
    hidden: false
  - id: tundra_ambience
    name: music_name_tundra_ambience
    audioEvent: environmental/tundraAmbience
    isAmbience: true
  - id: volcano_ambience    
    name: music_name_volcano_ambience
    audioEvent: environmental/volcanoAmbience
    isAmbience: true
  - id: tavern_ambience    
    name: music_name_tavern_ambience
    audioEvent: environmental/barAmbience
    isAmbience: true
    
  - id: weather_blizzard
    name: music_name_weather_blizzard
    audioEvent: environmental/weatherBlizzard
    isAmbience: true
  - id: weather_rain
    name: music_name_weather_rain
    audioEvent: environmental/weatherRain
    isAmbience: true
  - id: weather_sandstorm
    name: music_name_weather_sandstorm
    audioEvent: environmental/weatherSandstorm
    isAmbience: true
  - id: weather_storm
    name: music_name_weather_storm
    audioEvent: environmental/weatherStorm
    isAmbience: true
  - id: weather_windy
    name: music_name_weather_windy
    audioEvent: environmental/weatherWindy
    isAmbience: true

...
