---
# Properties are set to the following:
# hidden: false                  -- This allows it to be seen in the map editor and menus.
# placable: true                 -- This allows it to be placed in the map editor.

terrains:
  - id: sky
    name: terrain_name_sky
    defenceBonus: 0
    movementCost:
      flying: 1
      hovering: 1
    movementGroupType: air
    placeable: true

    # Volcano is placed on Layer 1 instead of the original Layer 0. This allows you to
    # see plains graphics below it to look nicer. It will cover up the lower layer anyway.
  - id: volcano
    name: terrain_name_volcano
    defenceBonus: 0
    movementCost: {}
    movementGroupType: land
    placeable: true
    hidden: false
    tilesets:
      0: plains
      1: volcano
...
