---

cutscene_sfx:
    # HIDDEN
  - id: spell_binding
    path: cutscene/spellBinding
    hidden: false
  - id: cutscene_ancient_door_open
    path: cutscene/ancientDoorOpen
    hidden: false
  - id: cutscene_requiem_break
    path: cutscene/requiemBreak
    hidden: false
  - id: cutscene_requiem_explode
    path: cutscene/requiemExplode
    hidden: false
  - id: cutscene_requiem_sheath
    path: cutscene/requiemSheath
    hidden: false
  - id: cutscene_sigrid_disappear
    path: cutscene/sigridDisappear
    hidden: false
  - id: cutscene_crown_fall
    path: cutscene/crownFall
    hidden: false
  - id: ship_die
    path: cutscene/shipDie
    hidden: false
  - id: huge_giant_step
    path: cutscene/hugeGiantStep
    hidden: false
  - id: teleport
    path: cutscene/teleportOut
    hidden: false
  - id: teleport_in
    path: cutscene/teleportIn
    hidden: false
  - id: bird_fly1
    path: cutscene/birdFly1
    hidden: false
  - id: bird_fly2
    path: cutscene/birdFly2
    hidden: false
  - id: bird_song1
    path: cutscene/birdSong1
    hidden: false
  - id: bird_song2
    path: cutscene/birdSong2
    hidden: false
  - id: treasure_stolen
    path: cutscene/treasureStolen
    hidden: false
  - id: rustling_bushes
    path: cutscene/bushRustle
    hidden: false
  - id: family_leaving_bushes
    path: cutscene/familyLeavingBushes
    hidden: false
  - id: family_leaving_cactus
    path: cutscene/familyLeavingCactii
    hidden: false
  - id: wulfar_carries_kids
    path: cutscene/familyCarry
    hidden: false
  - id: rope_unfurl
    path: cutscene/ropeThrow
    hidden: false
  - id: rope_slide
    path: cutscene/ropeSlide
    hidden: false
  - id: floran_ambush
    path: cutscene/floranAmbush
    hidden: false
  - id: meow
    path: cutscene/catMeow
    hidden: false
  - id: purr
    path: cutscene/catPurr
    hidden: false
...