---
# Improves readability of unlocked options by changing visual text.
# Some built-in tools have no string and display as #MISSING# unless manually defined here.
en-GB:
    # CUTSCENE BACKGROUNDS
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    ui_cutscene_background_forest_edited: Forest (Cactus edited)
    ui_cutscene_background_sand_forest_edited: Desert Vegetation (Less cactus)
    
    # CUTSCENE MUSIC
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    music_name_victory: Victory! (Does not loop)
    music_name_defeat: Defeat! (Does not loop)
    music_name_intro: Opening Groove (Does not loop)
    
    # CUTSCENE PROPS
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    ui_cutscene_prop_cherryship_sail: Sail - Cherrystone
    ui_cutscene_prop_ragnawarship_sail: Sail - Felheim (Torn)
    ui_cutscene_prop_tavernfire: Tavern Fireplace
    ui_cutscene_prop_cutscene_bush: Large Bush
    
    # CUTSCENE SHOUTS
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    
    
    # CUTSCENE EMOTES
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Mercia
    ui_cutscene_emote_crouching: Crouching
    ui_cutscene_emote_crouching_loop: Crouching - Still
    ui_cutscene_emote_hesitate: Crouching - Hesitating
    ui_cutscene_emote_reachingdown: Crouching - Reaching # Shared by: Sigrid
    ui_cutscene_emote_stab_loop: Stab - Still            # Shared by: Sigrid
    
    # Emeric      - None changed
    # Caesar      - None changed
    # Valder      - None changed
    # Sigrid      - None changed
    # Ragna       - None changed
    # Tenri       - None changed
    
    # Koji
    ui_cutscene_emote_mech: Giant Tenko

    # Ryota       - None changed
    # Greenfinger - None changed
    # Nuru        - None changed
    # Sedge       - None changed
    
    # Wulfar
    ui_cutscene_emote_bush: Bush - Sequence 1  # Shared by: Errol
    ui_cutscene_emote_bush2: Bush - Sequence 2 # Shared by: Errol
    ui_cutscene_emote_bush3: Bush - Hidden     # The first stage is the stationary bush, despite the numbering.
    ui_cutscene_emote_cactus: Cactus Sequence  #  Shared by: Errol, Orla
    ui_cutscene_emote_rope: Rope Sequence      # Shared by: Errol, Orla
    ui_cutscene_emote_grab: Pick up Twins

    # Twins        - None changed
    # Vesper       - None changed
    # Elodie       - None changed
    # Dark Mercia  - None changed
    # Mercival     - None changed
    
    # Errol
    ui_cutscene_emote_pet: Twins Petting Enid
    ui_cutscene_emote_petting: Petting Enid     # Shared by: Orla
    ui_cutscene_emote_cat: Enid Resting
    ui_cutscene_emote_catlay: Enid Laying Down
    ui_cutscene_emote_catsstop: Enid Stops Grooming
    
    # Orla          - None changed
    # Vesper (Boss) - None changed
    
    # CUTSCENE WALK TYPES
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    ui_cutscene_walk_type_mech: Giant Tenko
    ui_cutscene_walk_type_run_requiem: Run With Requiem
    ui_cutscene_walk_type_cat_running: Enid Running
    ui_cutscene_walk_type_run_crown: Crown
    ui_cutscene_walk_type_run_ragged: Crown - Ragged
...
