---
# Improves readability of unlocked options by changing visual text.
# Some built-in tools have no string and display as #MISSING# unless manually defined here.
en-GB:
    # CUTSCENE BACKGROUNDS
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    ui_cutscene_background_forest_edited: Forest (Cactus edited)
    ui_cutscene_background_sand_forest_edited: Desert Vegetation (Less cactus)
    
    # CUTSCENE MUSIC
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    music_name_victory: Victory! (Does not loop)
    music_name_defeat: Defeat! (Does not loop)
    music_name_intro: Opening Groove (Does not loop)
    
    # CUTSCENE PROPS
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    ui_cutscene_prop_cherryship_sail: Sail - Cherrystone
    ui_cutscene_prop_ragnawarship_sail: Sail - Felheim (Torn)
    ui_cutscene_prop_tavernfire: Tavern Fireplace
    ui_cutscene_prop_cutscene_bush: Large Bush
    
    # CUTSCENE SHOUTS
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Mercia
    mercia_attack5: 'Hyuh!'        # [Grunt 5]
    mercia_hit3: 'Short grunt'     # [Pain3]
    mercia_no1: '"No."'            # "No. [1]"
    mercian_no3: 'Anguished "No!"' # "No!"
    
    # Emeric      - None changed
    emeric_attack2: 'Grunt of Exertion 1' # Grunt [2]
    emeric_attack3: 'Grunt of Exertion 2' # Grunt of Exertion
    emeric_hit3: 'Surprised Grunt'        # [Pain 3]
    
    # Caesar
    caesar_bark2: 'High "Bark!"'  # [Bark 2]
    caesar_bark4: '"Bark!" 4'     # [Bark 4]
    caesar_bark5: '"Bark!" 5'     # [Bark 5]
    caesar_bark6: '"Bark!" 6'     # [Bark 6]
    caesar_hit2: 'Panicked Whine' # [Whine 2]
    caesar_hit3: 'Pained Whine'   # [Whine 3]
    
    # Valder
    valder_pain3: 'Surprised Grunt' # [Pain 3]
    
    # Sigrid
    sigrid_feralattack2: 'Short Grunt' # [Feral Attack 2]
    sigrid_feralattack3: 'Angry Grunt' # "Hyah!"
    
    # Ragna
    ragna_hit4: 'Frustrated Grunt'         # [Pain 4]
    ragna_laugh2: 'Excited Laugh'          # [Laugh 2]
    ragna_ughfine1: 'Angry "Ugh, fine!"'   # Ugh, fine! [1]
    ragna_ughfine1: 'Annoyed "Ugh, fine!"' # "Ugh, fine!"
    
    # Tenri
    tenri_attack1: 'Short Grunt' # [Attack 1]
    tenri_whatisthis2: 'Scared "What is this?"' # What is this? [2]
    
    # Koji        - None changed

    # Ryota
    ryota_attack4: 'Grunt of Exertion 1' # [Grunt 4]
    ryota_attack5: 'Grunt of Exertion 2' # Grunt of Exertion
    ryota_hit4: 'Surprised Grunt'        # [Pain 4]
    ryota_hit5: 'Agonised Grunt'         # [Pain 5]
    
    # Greenfinger
    greenfinger_hit4: 'Short Grunt'     # [Pain 4]
    greenfinger_hit5: 'Surprised Grunt' # [Pain 5]
    
    # Nuru        - None changed

    # Sedge
    sedge_blades: 'Sharpen blades' # [Blades sfx]
    
    # Wulfar       - None changed
    # Twins        - None changed 
    # Vesper       - None changed
    # Elodie       - None changed
    
    # Dark Mercia
    darkmercia_dyinggasp: 'Dying Gasp' # [Dying Gasp]

    # Mercival
    mercival_ghost_attack1: '[Ghostly] "Hyah!"'                                        # [Ghostly] [Grunt 1]
    mercival_ghost_attack2: '[Ghostly] "Hah!"'                                         # [Ghostly] [Grunt 2]
    mercival_ghost_attack3: '[Ghostly] Triumphant Grunt'                               # [Ghostly] [Grunt 3]
    mercival_ghost_attack4: '[Ghostly] Roar'                                           # [Ghostly] [Grunt 4]
    mercival_ghost_didnthavetobethisway: '[Ghostly] "It didn''t have to be this way."' # [Ghostly] It didn't have to be this way.
    mercival_ghost_donotfalter: '[Ghostly] "Do not falter."'                           # [Ghostly] Do not falter.
    mercival_ghost_donotlosehope: '[Ghostly] "Do not lose hope."'                      # [Ghostly] Do not lose hope.
    mercival_ghost_donotholdback: '[Ghostly] "Do not hold back."'                      # [Ghostly] Do not hold back.
    mercival_ghost_doyouunderstand: '[Ghostly] "Do you understand?"'                   # [Ghostly] Do you understand?
    mercival_ghost_emeric: '[Ghostly] "Emeric!"'                                       # [Ghostly] Emeric!
    mercival_ghost_farewell: '[Ghostly] "Farewell."'                                   # [Ghostly] Farewell.
    mercival_ghost_greetings: '[Ghostly] "Greetings."'                                 # [Ghostly] Greetings.
    mercival_ghost_hellooldfriend: '[Ghostly] "Hello old friend."'                     # [Ghostly] Hello old friend.
    mercival_ghost_hit1: '[Ghostly] Anguished Grunt'                                   # [Ghostly] [Pain 1]
    mercival_ghost_hit2: '[Ghostly] Pained Grunt'                                      # [Ghostly] [Pain 2]
    mercival_ghost_hit3: '[Ghostly] Surprised Grunt'                                   # [Ghostly] [Pain 3]
    mercival_ghost_hit4: '[Ghostly] Shocked Grunt'                                     # [Ghostly] [Pain 4]
    mercival_ghost_hmph: '[Ghostly] "Hmph."'                                           # [Ghostly] Hmph.
    mercival_ghost_iamwithyou: '[Ghostly] "I am with you."'                            # [Ghostly] I am with you.
    mercival_ghost_ibelieveinyou: '[Ghostly] "I believe in you."'                      # [Ghostly] I believe in you.
    mercival_ghost_itsinsafehands: '[Ghostly] "It''s in safe hands."'                  # [Ghostly] It's in safe hands.
    mercival_ghost_laugh1: '[Ghostly] Hearty Laugh'                                    # [Ghostly] [Laugh 1]
    mercival_ghost_laugh2: '[Ghostly] Amused Laugh'                                    # [Ghostly] [Laugh 2]
    mercival_ghost_laugh3: '[Ghostly] Triumphant Laugh'                                # [Ghostly] [Laugh 3]
    mercival_ghost_listen: '[Ghostly] "Listen."'                                       # [Ghostly] Listen.
    mercival_ghost_mercia1: '[Ghostly] Anguished "Mercia"'                             # [Ghostly] Mercia [1]
    mercival_ghost_mercia2: '[Ghostly] Pained "Mercia"'                                # [Ghostly] Mercia [2]
    mercival_ghost_mylittlebluebird1: '[Ghostly] Amused "My little bluebird."'         # [Ghostly] My little bluebird. [1]
    mercival_ghost_mylittlebluebird2: '[Ghostly] Warm "My little bluebird."'           # [Ghostly] My little bluebird. [2]
    mercival_ghost_no: '[Ghostly] "No."'                                               # [Ghostly] No.
    mercival_ghost_offwego: '[Ghostly] "Off we go!"'                                   # [Ghostly] Off we go!
    mercival_ghost_safehands: '[Ghostly] "Safe hands."'                                # [Ghostly] Safe hands.
    mercival_ghost_sigh: '[Ghostly] Sigh'                                              # [Ghostly] [Sigh]
    mercival_ghost_steelyourself: '[Ghostly] "Steel Yourself."'                        # [Ghostly] Steel Yourself.
    mercival_ghost_tellmercia: '[Ghostly] "Tell... Mercia."'                           # [Ghostly] Tell... Mercia.
    mercival_ghost_thankyou: '[Ghostly] "Thank you."'                                  # [Ghostly] Thank you.
    mercival_ghost_thelightshallnotfade: '[Ghostly] "The light shall not fade."'       # [Ghostly] The light shall not fade.
    mercival_ghost_themorethemerrier: '[Ghostly] "The more the merrier!"'              # [Ghostly] The more the merrier!
    mercival_ghost_thisshallserveuswell: '[Ghostly] "This shall serve us well!"'       # [Ghostly] This shall serve us well!
    mercival_ghost_toarms: '[Ghostly] "To arms!"'                                      # [Ghostly] To arms!
    mercival_ghost_togetherwestand: '[Ghostly] "Together we stand!"'                   # [Ghostly] Together we stand!
    mercival_ghost_verywellthen: '[Ghostly] "Very well then."'                         # [Ghostly] Very well then.
    mercival_ghost_weshallprevail:  '[Ghostly] "We shall prevail."'                    # [Ghostly] We shall prevail.
    mercival_ghost_what: '[Ghostly] "What?"'                                           # [Ghostly] What?
    mercival_ghost_whoops: '[Ghostly] "Whoops!"'                                       # [Ghostly] Whoops!
    mercival_ghost_worthyadversary: '[Ghostly] "A worthy adversary."'                  # [Ghostly] A worthy adversary
    mercival_ghost_yes: '[Ghostly] "Yes."'                                             # [Ghostly] Yes.
    mercival_ghost_youhaveneverletmedown: '[Ghostly] "You have never let me down."'    # [Ghostly] You have never let me down.
    mercival_ghost_youhavetoknowthesethings: '[Ghostly] "You have to know..."'         # [Ghostly] You have to know these things
    mercival_ghost_youmustlisten: '[Ghostly] "You must listen!"'                       # [Ghostly] You must listen!
    mercival_hit3: 'Surprised Grunt'                                                   # [Pain 3]
    
    # Errol
    errol_wow: 
    
    # Orla
    twins_da: '[Together] "Da!"' # "Da!"
    twins_hit: '[Together] Shocked' # Both Shocked
    twins_laugh: '[Together] Laughing' # Both Laughing
    twins_wondertwinpowers: '[Together] "Wonder Twin Powers!"' # "Wonder Twin Powers, activate!"
    
    # Vesper (Boss) - None changed
    
    # CUTSCENE EMOTES
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Mercia
    ui_cutscene_emote_crouching: Crouching
    ui_cutscene_emote_crouching_loop: Crouching - Still
    ui_cutscene_emote_hesitate: Crouching - Hesitating
    ui_cutscene_emote_reachingdown: Crouching - Reaching # Shared by: Sigrid
    ui_cutscene_emote_stab_loop: Stab - Still            # Shared by: Sigrid
    
    # Emeric      - None changed
    # Caesar      - None changed
    # Valder      - None changed
    # Sigrid      - None changed
    # Ragna       - None changed
    # Tenri       - None changed
    
    # Koji
    ui_cutscene_emote_mech: Giant Tenko

    # Ryota       - None changed
    # Greenfinger - None changed
    # Nuru        - None changed
    # Sedge       - None changed
    
    # Wulfar
    ui_cutscene_emote_bush: Bush - Sequence 1  # Shared by: Errol
    ui_cutscene_emote_bush2: Bush - Sequence 2 # Shared by: Errol
    ui_cutscene_emote_bush3: Bush - Hidden     # The first stage is the stationary bush, despite the numbering.
    ui_cutscene_emote_cactus: Cactus Sequence  #  Shared by: Errol, Orla
    ui_cutscene_emote_rope: Rope Sequence      # Shared by: Errol, Orla
    ui_cutscene_emote_grab: Pick up Twins

    # Twins        - None changed
    # Vesper       - None changed
    # Elodie       - None changed
    # Dark Mercia  - None changed
    # Mercival     - None changed
    
    # Errol
    ui_cutscene_emote_pet: Twins Petting Enid
    ui_cutscene_emote_petting: Petting Enid     # Shared by: Orla
    ui_cutscene_emote_cat: Enid Resting
    ui_cutscene_emote_catlay: Enid Laying Down
    ui_cutscene_emote_catsstop: Enid Stops Grooming
    
    # Orla          - None changed
    # Vesper (Boss) - None changed
    
    # CUTSCENE WALK TYPES
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    ui_cutscene_walk_type_mech: Giant Tenko
    ui_cutscene_walk_type_run_requiem: Run With Requiem
    ui_cutscene_walk_type_cat_running: Enid Running
    ui_cutscene_walk_type_run_crown: Crown
    ui_cutscene_walk_type_run_ragged: Crown - Ragged
...
